services:
  app:
    build:
      context: ../desafio-gps-poi
      dockerfile: Dockerfile
    container_name: spring_app_zulu21
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/poi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: poi
    ports:
      - "5433:5433"

volumes:
  postgres_data: